# Generated by Django 2.1.7 on 2019-04-15 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(blank=True, choices=[('Best', 'Best'), ('Good', 'Good'), ('Avoid', 'Avoid')], default='Best', max_length=20, null=True)),
                ('product_name', models.CharField(blank=True, default='', max_length=400)),
                ('product_category', models.CharField(blank=True, default='', max_length=400)),
                ('accreditation', models.CharField(blank=True, default='', max_length=400)),
                ('availability', models.CharField(blank=True, default='', max_length=358)),
                ('location', models.CharField(blank=True, default='', max_length=400)),
                ('address', models.CharField(blank=True, default='', max_length=400)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
