# Generated by Django 2.1.7 on 2019-04-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_remove_snippet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='availability',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
