# Generated by Django 2.1.7 on 2019-04-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_remove_snippet_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='rating',
            field=models.CharField(blank=True, choices=[('Best', 'Best'), ('Good', 'Good'), ('Avoid', 'Avoid')], default='', max_length=400),
        ),
    ]
