# Generated by Django 2.1.7 on 2019-04-27 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20190426_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='', max_length=400)),
                ('coordinate', models.CharField(blank=True, default='', max_length=400)),
                ('location_description', models.CharField(blank=True, default='', max_length=1000)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Snippet')),
            ],
        ),
    ]
