# Generated by Django 2.1.7 on 2019-04-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20190427_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='product_id',
            new_name='PID',
        ),
    ]
