# Generated by Django 2.1.7 on 2019-04-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20190427_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='PID',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
