# Generated by Django 2.1.7 on 2019-04-27 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20190427_0519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='PID',
            new_name='product_id',
        ),
    ]
