# Generated by Django 2.1.7 on 2019-04-27 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_auto_20190427_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='product_id',
        ),
        migrations.AddField(
            model_name='report',
            name='PID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='snippets.Snippet'),
            preserve_default=False,
        ),
    ]
