# Generated by Django 2.2.1 on 2019-05-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0010_auto_20190505_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='PID',
        ),
        migrations.AddField(
            model_name='report',
            name='product_id',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
