# Generated by Django 2.2.1 on 2019-05-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0011_auto_20190505_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, default='', max_length=400)),
                ('user_age', models.CharField(blank=True, default='', max_length=400)),
                ('user_gender', models.CharField(blank=True, default='', max_length=400)),
                ('product_type', models.CharField(blank=True, default='', max_length=400)),
            ],
        ),
    ]
