# Generated by Django 2.2.1 on 2019-05-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0012_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='num',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
