# Generated by Django 2.2.1 on 2019-05-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0013_statistics_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='accreditation',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='report',
            name='email',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
